flowchart TD
    subgraph "Malic Acid (C2H4(COOH)2)"
    direction LR
    1["OH"] --- 2["C"]
    3["O"] === 2
    4["C"] --- 2
    5["H"] --- 4
    6["H"] --- 4
    7["C"] --- 4
    8["H"] --- 7
    9["H"] --- 7
    10["C"] --- 7["C"]
    30["O"] === 10
    40["OH"] --- 10
    end
    subgraph "Benzaldehyde (C6H5CHO)"
    direction LR
    B["C"] === C
    C --- D["C"]
    D === E["C"]
    E --- F["C"]
    F === G["C"]
    G --- B
    J["H"] --- C
    K["H"] --- D
    L["H"] --- E
    M["H"] --- F
    N["H"] --- G
    B --- P["C"]
    Q["O"] === P
    R["H"] --- P
    end
    subgraph "Butyl Alcohol (C4H90H)"
    direction LR
    b["C"] --- c["C"]
    d["C"] --- b
    e["H"] --- c
    f["H"] --- b
    g["H"] --- c
    h["H"] --- b
    c --- i["OH"]
    j["C"] --- d
    k["H"] --- d
    l["H"] --- d
    m["H"] --- j
    n["H"] --- j
    o["H"] --- j
    end