---
title: Organic Compounds
---
flowchart TB
    A[Organic Compounds] --> B[Hydrocarbons]
    B --> C["Alkanes"]
    B --> D["Alkenes"]
    B --> E["Alkynes"]
    A --> F["Oxygenous"]
    F --> G["Single Bonds"]
    F --> H["Double Bonds"]
    G --> I["Alcohols"]
    G --> J["Ethers"]
    H --> K["Aldehydes"]
    H --> L["Ketones"]
    H --> M["Carboxyl Acids"]
    H --> N["Esters"]
    A --> O["Nitrogenous"]
    O --> P["Amides"]
    O --> Q["Amines"]
    B --> R[Arenes]
    H --> P
    A --> S["Sulfurous"]
    S --> Thiols